{
 "title": "Monitoreo Taller Java",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Sucive OK cobro",
   "type": "graph",
   "description": "Suma los exitos de pagos por Sucive a vehiculos nacionales en intervalos de 10s. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "suciveOKCobroSucive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peaje OK Cantidad Vehiculo Nacional",
   "type": "graph",
   "description": "Suma los exitos de las pasadas por el peaje para vehiculos NACIONALES en intervalos de 10s. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "peajeOKPagoRealizadoNacional",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peaje OK Cantidad Vehiculo Extranjero",
   "type": "graph",
   "description": "Suma los exitos de las pasadas por el peaje para vehiculos EXTRANJEROS en intervalos de 10s. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Medios Pago ERROR Tarjeta Rechazada",
   "type": "graph",
   "description": "suma los fallos al cobrar por tarjeta en intervalos de 10 segundos de tiempo. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mediospagoERRORCobroTarjetaRechazado",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gestion ERROR Pago Tarjeta Rechazado",
   "type": "graph",
   "description": "suma los rechazos al procesar los pagos con tarjeta en intervalos de 10 segundos de tiempo. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gestionERRORTarjetaRechazada",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gestion ERROR Cliente No Encontrado por TAG",
   "type": "graph",
   "description": "suma los fallos al buscar un Cliente Telepeaje en intervalos de 10 segundos de tiempo. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gestionERRORClienteTelepeajeNoEncontrado",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Medios Pago OK Cobro con Tarjeta",
   "type": "graph",
   "description": "suma los exitos al procesar el pago en con la tarjeta en intervalos de 10 segundos de tiempo. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mediospagoOKCobroTarjeta",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gestion ERROR Saldo Insuficiente",
   "type": "graph",
   "description": "suma los fallos al realizar el pre pago por saldo insuficiente intervalos de 10 segundos de tiempo. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gestionERRORSaldoInsuficiente",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gestion OK Post Pago",
   "type": "graph",
   "description": "suma los existos de los post pagos realizados en intervalos de 10 segundos de tiempo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gestionOKPostPago",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gestion OK Pre Pago",
   "type": "graph",
   "description": "suma los existos de los pre pagos realizados en intervalos de 10 segundos de tiempo. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gestionOKPrePago",
     "query": "SELECT sum(\"value\") FROM \"gestionOKPrePago\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}